# steps:
# - name: 'docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/graffix-snatcher', '.' ]

# # By default, all built docker images will be lost once the build is complete.
# # Rather than writing a build step to push this image, you can simply list the
# # image below and it will automatically be uploaded to Google Cloud Container
# # Registry.
# images:
# - 'gcr.io/$PROJECT_ID/graffix-snatcher'

# # You can organize your builds with tags
# tags: ['gcp-cloud-build-sample-build']

steps:
  - name: gcr.io/$PROJECT_ID/docker-compose
    id: Build
    args: [ 'build' ]
    # args:
    #   - build
    #   - '--no-cache'
    #   - '-t'
    #   - '$_IMAGE_NAME'
    #   - .
    #   - '-f'
    #   - Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: Push
    args: [ 'push', '$_IMAGE_NAME' ]
    # args:
    #   - push
    #   - '$_IMAGE_NAME'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_IMAGE_NAME'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    entrypoint: gcloud
images:
  - '$_IMAGE_NAME'
options:
  env: [ 'IMAGE_NAME=${_IMAGE_NAME}' ]
substitutions:
  _IMAGE_NAME: '${_GCR_HOSTNAME}/${PROJECT_ID}/${REPO_NAME}/${_SERVICE_NAME}'
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: graffix-snatcher
